# Mod Loading Information
modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

# Create: Electrified Config
[[mods]]
modId="createlectrified"
version="${file.jarVersion}"
displayName="Create: Electrified"
logoFile="createlectrified.png"
credits="Created by TardisModding"
authors="TardisEngineer"
description='''
Work in progress!
'''

# Dependency for Forge
[[dependencies.createlectrified]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

# Dependency for Minecraft
[[dependencies.createlectrified]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
   side="BOTH"

# Dependency for Create
[[dependencies.createlectrified]]
    modId="create"
    mandatory=true
    versionRange="[0.5.0.f,)"
    ordering="NONE"
    side="BOTH"

